// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeMedia(arg1) {
  return window['go']['main']['App']['AnalyzeMedia'](arg1);
}

export function ConvertVideo(arg1, arg2) {
  return window['go']['main']['App']['ConvertVideo'](arg1, arg2);
}

export function GetOSName() {
  return window['go']['main']['App']['GetOSName']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UploadChunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadChunk'](arg1, arg2, arg3);
}
