// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeMedia(arg1:string):Promise<main.MediaInfo>;

export function ConvertVideo(arg1:string,arg2:main.EncodeOptions):Promise<main.ConvertResult>;

export function Greet(arg1:string):Promise<string>;

export function UploadChunk(arg1:string,arg2:string,arg3:number):Promise<string>;
